# Generated by Django 4.2.7 on 2023-11-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Ambulancia', models.IntegerField()),
                ('Marca', models.CharField(max_length=60)),
                ('Modelo', models.CharField(max_length=60)),
                ('Estado', models.CharField(max_length=60)),
            ],
        ),
    ]
