# Generated by Django 4.2.7 on 2023-11-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Medico', models.IntegerField()),
                ('Nombre_Completo', models.CharField(max_length=60)),
                ('Especialidad', models.CharField(max_length=60)),
                ('Numero_de_Telefono', models.CharField(max_length=60)),
            ],
        ),
    ]
